# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7dbd600b67d1dcbb81b4f0e7581501c141957dcd6721b31426750cb1910bfdacebe53bb2d2865491405a8e7255e9f6facb9c12f4612278f1901d946d827b8ef

test:
  secret_key_base: b1e99b05bc9c24e4b085621f2eccaaafe0e58183aca470657a3d2bbf6ac4b97be78eafdde84cbf62efc83769265d99e76ada643da6d6ef3b855ba30fcbc569ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
